"""Compile linked, inferred catalogue hydraulics into the production shared kernel.

This is asset generation, not a fluid simulation or a class-match test. Rocks,
river-wide drops and unregistered coordinate frames cannot be replaced by waves.
All lengths/heights here are authored hypotheses, never measured bathymetry.
"""
import argparse
import hashlib
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / 'unreal/Plugins/RaftSim/Source/RaftSimWater/Public/RaftSimNamedRapidProfiles.inl'
CATALOGUES = {
    'L_Hance': 'colorado_river_grand_canyon_rowing/observed_rapids/hance_observed_rapids.json',
    'L_UpperHuacas': 'pacuare_river_costa_rica/observed_rapids/huacas_observed_rapids.json',
    'L_Terminator': 'futaleufu_river_chile/observed_rapids/terminator_observed_rapids.json',
    'L_LavaCanyon': 'chilko_river_bc/observed_rapids/lava_canyon_observed_rapids.json',
    'L_Zambezi': 'zambezi_batoka_gorge/observed_rapids/batoka_run_observed_rapids.json',
}
# Keep the already native-tested reference sites exactly, not another set on
# top of them. Director's normal was explicitly verified against hull current.
EXISTING = {
    'L_Hance': {'emilios_hole', 'giants_lateral', 'bottom_hole'},
    'L_Zambezi': {'r7_directors_wave', 'r7_the_crease', 'r7_land_of_the_giants'},
}
KINDS = {'wave_train', 'pour_over', 'ledge_hole', 'lateral', 'diagonal'}


def lateral_centres(width):
    # A single roller has a 9.6 m compact span. Keep centres <=6 m apart;
    # strongest-owner current selection prevents summing multiple roller forces.
    count = max(1, math.ceil(max(0., width - 9.6) / 6.) + 1)
    extent = max(0., width - 9.6)
    return [0.] if count == 1 else [-extent/2 + i*extent/(count-1) for i in range(count)]


def compile_catalogue(name, catalogue):
    if catalogue['station_frame'] != 'scenario':
        raise ValueError(f'{name}: evidence stations need an explicit registered transform')
    output = []
    for f in catalogue['features']:
        if f['type'] not in KINDS or f['id'] in EXISTING.get(name, set()):
            continue
        # Commercial Suicide remains portage, not a runnable challenge upgrade.
        if name == 'L_Zambezi' and f['id'].startswith('r9_'):
            continue
        for field in ('station_m', 'lateral_m', 'width_m'):
            if not isinstance(f.get(field), (int, float)) or not math.isfinite(f[field]):
                raise ValueError(f'{name}/{f["id"]}: invalid {field}')
        if not 0 < f['width_m'] <= 100:
            raise ValueError('Invalid feature width')
        wave = f['type'] == 'wave_train'
        count = f.get('waves', 1) if wave else 1
        if not isinstance(count, int) or not 1 <= count <= 20:
            raise ValueError('Invalid wave count')
        spacing = float(f.get('wavelength_m', 16.))
        if not math.isfinite(spacing) or not 6 <= spacing <= 40:
            raise ValueError('Invalid wavelength')
        # Existing kernel's physical-height limit is 1.2 m. A 3 m ledge is
        # NOT flattened into a 3 m wave: bed/collision must supply its drop.
        amplitude = float(f.get('amplitude_m', .8 if wave else 1.0))
        angle = float(f.get('angle_deg', 0.))
        if not math.isfinite(amplitude) or amplitude <= 0 or not math.isfinite(angle):
            raise ValueError(f'{name}/{f["id"]}: invalid amplitude or angle')
        height = min(1.2, amplitude)
        # The catalogue's Bidwell description specifies a LEFTWARD shove.
        # Roller return opposes its normal; +35 would shove the opposite way.
        if name == 'L_LavaCanyon' and f['id'] == 'bidwell_entrance_lateral':
            angle = -35.
        for i in range(count):
            for offset in lateral_centres(f['width_m']):
                output.append((f['id'], f['station_m'] + i*spacing,
                               f['lateral_m'] + offset, angle, height,
                               5. if wave else 3., .45 if wave else .9))
    return output


def render():
    lines = ['// Generated by build_named_rapid_profiles.py; do not edit.',
             '// Inferred geometry/height/spacing; no class or survey claim.',
             '// Included inside Features() after the native-tested reference sites.']
    for name, relative in CATALOGUES.items():
        path = ROOT / 'physics/data/real_world' / relative
        catalogue = json.loads(path.read_text(encoding='utf-8'))
        rows = compile_catalogue(name, catalogue)
        lines += [f'// Source: {relative}',
                  f'// SHA256: {hashlib.sha256(path.read_bytes()).hexdigest()}',
                  f'if (Map.EndsWith(TEXT("{name}")))', '{']
        previous = None
        for feature, *values in rows:
            if feature != previous:
                lines.append(f'    // {feature}')
                previous = feature
            nums = [f'{v:.6f}' + ('f' if i >= 3 else '') for i, v in enumerate(values)]
            lines.append('    Result.Add({' + ','.join(nums) + '});')
        lines.append('}')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != content:
            raise SystemExit('Generated named profiles are stale; regenerate before building.')
    else:
        OUTPUT.write_text(content)
    print(f'{"Verified" if args.check else "Generated"}: {OUTPUT}')
