#include "RaftSimRunAudioDirector.h"

#include "Components/AudioComponent.h"
#include "Engine/GameInstance.h"
#include "EngineUtils.h"
#include "RaftSimPhysicsBridgeSubsystem.h"
#include "RaftSimRaftActor.h"
#include "RaftSimWaterRuntimeAdapter.h"
#include "Sound/SoundWaveProcedural.h"

namespace
{
constexpr int32 kSampleRate = 44100;

// Fill a procedural wave with looping shaped noise resembling river hiss.
void GenerateWaterNoise(USoundWaveProcedural* Wave)
{
    Wave->SetSampleRate(kSampleRate);
    Wave->NumChannels = 1;
    Wave->Duration = INDEFINITELY_LOOPING_DURATION;
    Wave->SoundGroup = SOUNDGROUP_Default;
    Wave->bLooping = true;
}
}

ARaftSimRunAudioDirector::ARaftSimRunAudioDirector()
{
    PrimaryActorTick.bCanEverTick = true;

    AmbienceAudio = CreateDefaultSubobject<UAudioComponent>(TEXT("AmbienceAudio"));
    SetRootComponent(AmbienceAudio);
    AmbienceAudio->bAutoActivate = false;
    AmbienceAudio->bIsUISound = false;
}

void ARaftSimRunAudioDirector::BeginPlay()
{
    Super::BeginPlay();

    if (const UGameInstance* GI = GetGameInstance())
    {
        Bridge = GI->GetSubsystem<URaftSimPhysicsBridgeSubsystem>();
    }
    if (TActorIterator<ARaftSimRaftActor> It(GetWorld()); It)
    {
        Raft = *It;
    }
    if (Raft != nullptr)
    {
        LastSwimmerCount = Raft->GetSwimmerCount();
    }

    // Build the looping water ambience. Procedural noise is generated by the
    // audio render thread via OnGeneratePCMAudio-style streaming; here we set
    // up the wave and start it. Silent no-ops without an audio device.
    WaterNoise = NewObject<USoundWaveProcedural>(this);
    GenerateWaterNoise(WaterNoise);
    AmbienceAudio->SetSound(WaterNoise);
    AmbienceAudio->SetVolumeMultiplier(0.0f);
    AmbienceAudio->Play();
}

void ARaftSimRunAudioDirector::Tick(float DeltaSeconds)
{
    Super::Tick(DeltaSeconds);
    if (Raft == nullptr)
    {
        return;
    }

    FRaftSimWaterAudioTelemetry Telemetry;
    const float RaftSpeed = Raft->GetRaftVelocity().Size();
    Telemetry.FlowSpeedMetersPerSecond = RaftSpeed;

    if (Bridge != nullptr)
    {
        if (const URaftSimWaterRuntimeAdapter* Water = Bridge->GetWaterRuntime())
        {
            FRaftSimWaterSample Sample;
            if (Water->SampleWaterAtWorldPosition(Raft->GetActorLocation(), Sample) && Sample.bWet)
            {
                const float FlowSpeed = Sample.VelocityMetersPerSecond.Size2D();
                Telemetry.FlowSpeedMetersPerSecond = FMath::Max(RaftSpeed, FlowSpeed);
                const float Froude =
                    FlowSpeed / FMath::Sqrt(9.80665f * FMath::Max(Sample.DepthMeters, 0.1f));
                Telemetry.Aeration = FMath::Clamp((Froude - 0.6f) / 0.8f, 0.0f, 1.0f);
                Telemetry.Turbulence = Telemetry.Aeration;
            }
        }
    }

    // Flip impacts drive the impact layer.
    const int32 Swimmers = Raft->GetSwimmerCount();
    if (Swimmers > LastSwimmerCount)
    {
        Telemetry.RaftImpactImpulse = 1.0f;
    }
    LastSwimmerCount = Swimmers;

    CurrentParameters = RaftSimAudio::BuildWaterAudioParameters(Telemetry);

    // River roar sets the ambience loudness; feature intensity lifts pitch.
    if (AmbienceAudio != nullptr)
    {
        AmbienceAudio->SetVolumeMultiplier(FMath::Clamp(CurrentParameters.RiverRoar, 0.0f, 1.0f));
        AmbienceAudio->SetPitchMultiplier(
            1.0f + 0.25f * FMath::Clamp(CurrentParameters.RapidFeatureIntensity, 0.0f, 1.0f));
    }
}
