[out:json][timeout:180];
relation(9751030);
out geom;
(
  node(-43.45,-72.15,-43.15,-71.70)["whitewater"];
  node(-43.45,-72.15,-43.15,-71.70)["whitewater:rapid_grade"];
  node(-43.45,-72.15,-43.15,-71.70)["whitewater:section_grade"];
  node(-43.45,-72.15,-43.15,-71.70)["waterway"="rapids"];
  node(-43.45,-72.15,-43.15,-71.70)["natural"="rapids"];
  way(-43.45,-72.15,-43.15,-71.70)["whitewater"];
  way(-43.45,-72.15,-43.15,-71.70)["waterway"="rapids"];
  way(-43.45,-72.15,-43.15,-71.70)["natural"="water"]["water"="river"];
  relation(-43.45,-72.15,-43.15,-71.70)["natural"="water"]["water"="river"];
  way(-43.45,-72.15,-43.15,-71.70)["bridge"="yes"]["highway"];
);
out geom;
