"""Headless physics foundation for the rafting simulator."""

from .math3d import Quaternion, Vec3
from .math2d import Vec2
from .raft2d import (
    PaddleCommand2D,
    Raft2DConfig,
    Raft2DSimulation,
    Raft2DState,
    Raft2DStepResult,
    default_forward_paddle_commands,
)
from .river2d import (
    GeneratedRiver2D,
    River2DParameters,
    RiverFeature2D,
    RiverSample2D,
    RiverValidation2D,
    generate_river_2d,
)
from .scenario2_5d import (
    BoundaryCondition2_5D,
    BoundaryHydrographSample2_5D,
    Feature2_5D,
    FixtureScenario2_5DParameters,
    GridSpec2_5D,
    InitialWaterState2_5D,
    Probe2_5D,
    ProceduralScenario2_5DParameters,
    RaftParameters2_5D,
    Scenario2_5D,
    ScenarioMetadata2_5D,
    ScenarioValidation2_5D,
    ValidationCheck2_5D,
    generate_fixture_scenario2_5d,
    generate_procedural_scenario2_5d,
    read_scenario2_5d_package,
)
from .sim import Simulation, SimulationConfig, SimulationSystem
from .state import BodyState
from .telemetry import ForceContribution, TelemetryFrame, TelemetryRecorder
from .backends import (
    BackendCapabilities,
    BackendStatus,
    BackendUnavailableError,
    ChronoSimulation,
    PhysicsBackend,
    ProjectChronoBackend,
    PurePythonBackend,
    backend_statuses,
    create_backend,
    select_backend,
)

__all__ = [
    "BackendCapabilities",
    "BackendStatus",
    "BackendUnavailableError",
    "BodyState",
    "ChronoSimulation",
    "ForceContribution",
    "PhysicsBackend",
    "ProjectChronoBackend",
    "PurePythonBackend",
    "Quaternion",
    "Simulation",
    "SimulationConfig",
    "SimulationSystem",
    "TelemetryFrame",
    "TelemetryRecorder",
    "Vec3",
    "Vec2",
    "PaddleCommand2D",
    "Raft2DConfig",
    "Raft2DSimulation",
    "Raft2DState",
    "Raft2DStepResult",
    "GeneratedRiver2D",
    "River2DParameters",
    "RiverFeature2D",
    "RiverSample2D",
    "RiverValidation2D",
    "BoundaryCondition2_5D",
    "BoundaryHydrographSample2_5D",
    "Feature2_5D",
    "FixtureScenario2_5DParameters",
    "GridSpec2_5D",
    "InitialWaterState2_5D",
    "Probe2_5D",
    "ProceduralScenario2_5DParameters",
    "RaftParameters2_5D",
    "Scenario2_5D",
    "ScenarioMetadata2_5D",
    "ScenarioValidation2_5D",
    "ValidationCheck2_5D",
    "backend_statuses",
    "create_backend",
    "default_forward_paddle_commands",
    "generate_fixture_scenario2_5d",
    "generate_procedural_scenario2_5d",
    "generate_river_2d",
    "read_scenario2_5d_package",
    "select_backend",
]
